### ISSUE TITLE
concerning the vim color file

### ISSUE THREAD

**Issue by SolarAquarion** [herecura/vim#2]
Instead of downloading the vim color file wouldn't it be better to just require vim-colorschemes https://aur.archlinux.org/packages/vim-colorschemes

**Comment by BlackIkeEagle** [comment]
@SolarAquarion I might just need to remove the colorscheme since I've not bothered checking for updates

**Comment by SolarAquarion** [comment]
removing the colorscheme would be a good idea just feature a .install which post upgrade/post install says install a colorscheme of your choice and put colorscheme $colorscheme in your vimrc

**Comment by BlackIkeEagle** [comment]
the additional colorscheme and some other additional files were removed
